添加“未选中”视图、生成解锁圣遗物对应的 lock.json 的选项
LeiShi1313/genshin-aritifact-builds pull request #5
Opened 2023-03-10 06:09 UTC by wengh

目前背包里的圣遗物全部都是锁定状态，所以想用这个工具筛选出相对差的做狗粮，用 yas-lock 解锁，腾出一些库存空间。所以添加了分别导出仅加锁、仅解锁、和全部变更对应的 `lock.json` 的按钮。

添加“未选中”视图是为了方便确认要解锁的圣遗物。

![image](https://user-images.githubusercontent.com/16470555/224236751-19518afc-b848-4341-982c-65853e4ce437.png)

2023-03-10 06:12 UTC, wengh commented
预览：https://genshin-artifact-analyzer-wengh.vercel.app

2023-03-12 11:48 UTC, LeiShi1313 requested changes

2023-03-12 11:48 UTC, LeiShi1313 commented on src/features/artifacts/ArtifactsUpload.jsx
> +    { name: "isInverted", defaultValue: false, replace: false },
这个参数严格来讲跟其他的筛选不是一类， 它不能和其他的筛选条件一起使用；其次invert也不太能体现这个筛选条件的实际作用， isSelected就挺好的

2023-03-12 11:48 UTC, LeiShi1313 commented on src/features/artifacts/ArtifactsUpload.jsx
> +  const levelFilterFn = useCallback(
把等级的筛选单独写出来的作用是什么？是性能上的考虑吗

2023-03-12 11:48 UTC, LeiShi1313 commented on src/features/artifacts/ArtifactsUpload.jsx
> +    [sortedArtifacts, filterFn]
这多出来的4个变量除了增加复杂度我没有看到实质的作用，除了selected和unselected，其他似乎都是中间变量，那么抛弃原有的filteredArtifacts就显得没那么有必要？

2023-03-12 11:48 UTC, LeiShi1313 commented on src/features/artifacts/ArtifactsUpload.jsx
> +  const handleDownloadYasLock = useCallback(({ toLock = [], toUnlock = [] }) => {
完全没有必要把这两个变量传进来，只需要根据`isInverted`的状态重新计算一边就可以了

2023-03-12 11:48 UTC, LeiShi1313 commented on src/features/artifacts/ArtifactsUpload.jsx
> +  const handleDownloadYasLock = useCallback(({ toLock = [], toUnlock = [] }) => {
Ah，说错了，应该是只需要传入一个变量，比如`selected=ALL|LOCK_ONLY|UNLOCK_ONLY`，然后根据这个变量重新计算就可以了

2023-03-12 11:48 UTC, LeiShi1313 commented on src/features/artifacts/ArtifactsFilter.jsx
> +          </span>
基于我在其他地方写的观点，我不觉得这个应该作为一个筛选条件，即使真的需求，也应该在独立的一行，以示区别于其他筛选条件，可能的话，其他的筛选条件最好还需要变成disabled。

2023-03-12 11:51 UTC, LeiShi1313 commented on public/locales/zh/common.json
> +    "All": "全部",
全部表示什么让人造成费解，建议改成`加锁并解锁`或者`加解锁`

2023-03-12 11:58 UTC, LeiShi1313 commented
谢谢PR，总体来说没什么大问题，但是有几点想要你稍微改一下的：
- `isInverted`的这个筛选条件，连同在[ArtifactsFilter.jsx](https://github.com/LeiShi1313/genshin-aritifact-analyzer/pull/5/files/91850e82320a315e683c8d614a38e3a2c8518ad0#diff-13c63eb241b705f5c621de5bd0e7ff7f5c7c62f455ebc302ec60c28c988ff63f)的修改，希望可以放到另一个PR，或者根据我的意见修改一下，或者你也可以提出你的想法。我认为这个PR是不需要这些改动的，下条说明
- `handleDownloadYasLock`不需要传入数值参数， 只需要要筛选的条件传进去，然后在下载的时候重新计算一下即可，这样的话,`selectedArtifacts`和`unselectedArtifacts `也可以去掉，`isInverted`在这个PR也不是必须的了

2023-03-12 17:25 UTC, wengh commented on src/features/artifacts/ArtifactsUpload.jsx
> +    { name: "isInverted", defaultValue: false, replace: false },
我认为这个和排序是同一类的参数，只影响显示的内容，不影响最终导出的文件。或许叫做isSelectedView更合适一些？

2023-03-12 17:40 UTC, wengh commented on src/features/artifacts/ArtifactsUpload.jsx
> +  const levelFilterFn = useCallback(
实际使用中，从用户的角度，我会希望等级的筛选同时作用在加锁和解锁上。比如设置等级范围0-1后导出解锁文件，并不应该解锁全部2-20级的圣遗物，而是应该只解锁0-1级，不满足稀有度和匹配度阈值的圣遗物。

2023-03-12 17:41 UTC, LeiShi1313 commented on src/features/artifacts/ArtifactsUpload.jsx
> +    { name: "isInverted", defaultValue: false, replace: false },
这我倒无所谓，只是这几点我比较在意：
- 不能跟其他的筛选条件一起使用
- 作为一个checkbox，一般你只需要显示当前的状态就可以了，现在selected和unselected都显示了会让人搞不清当前到底是哪个状态

2023-03-12 18:07 UTC, wengh commented on src/features/artifacts/ArtifactsUpload.jsx
> +    { name: "isInverted", defaultValue: false, replace: false },
这个是可以跟其他筛选跳进一起使用的。我也觉得现在这样的ui没能准确地表达参数的作用。

或许应该回到最初的目的：既然增加了导出解锁圣遗物的选项，那么也应该有相应的预览界面。

整体的ui怎么实现呢…… 我又重新想了想，或许可以这样：
- 把圣遗物按分成四类，分别对应`锁定->未锁定`、`未锁定->锁定`等等。可以用图标表达
- 筛选ui里加一个复选框，让用户自行选择要查看/导出的圣遗物加解锁类型
- 生成lock.json时只导出选中的圣遗物加解锁类型。比如如果选中了`锁定->锁定`、`未锁定->锁定`，那么就只生成加锁需要的lock.json

关于这个，你有什么其他的思路或者建议吗？

2023-03-12 23:25 UTC, LeiShi1313 commented on src/features/artifacts/ArtifactsUpload.jsx
> +    { name: "isInverted", defaultValue: false, replace: false },
我觉得生成lock.json这个2按钮和显示“选中”/“未选中”的筛选是可以分开的。你的做法相当于把现在lock.json的3个选项也做成了筛选条件并且把筛选结果集成到了UI上。我觉得还是可以分开，lock.json还是有3个选项，但是筛选条件加一个可以显示未被选中的圣遗物的toggle，UI上可以做灰一点，这样显示上也同样直观。差别只是没有“仅显示未被选中的圣遗物”这个功能了，我也没想到有什么场景会需要这样的显示结果

2023-03-13 00:51 UTC, wengh commented on src/features/artifacts/ArtifactsUpload.jsx
> +    { name: "isInverted", defaultValue: false, replace: false },
我还是认为“仅显示未被选中的圣遗物”的功能是有必要的。之前调整参数的时候，我是看着未选中的圣遗物里面，稀有度/匹配度最高的，来判断参数是否合理，会不会不小心把我认为未来可期的圣遗物解锁。

我想可以按照你描述的这样，但是再加一个“显示选中”的toggle，这样就可以实现只显示未选中的功能了。然后因为可以同时勾选两个选项，所以应该在列表中区分选中和未选中的圣遗物。

2023-03-14 16:38 UTC, LeiShi1313 commented on src/features/artifacts/ArtifactsUpload.jsx
> +    { name: "isInverted", defaultValue: false, replace: false },
```
我是看着未选中的圣遗物里面，稀有度/匹配度最高的，来判断参数是否合理
```
这个功能并不必需“仅显示未被选中的圣遗物”，事实上，显示全部（选中+未选中）圣遗物这样的UI会让参数微调显得更方便点。
我为什么不怎么喜欢“仅显示未被选中的圣遗物”这个功能，是因为如果一旦做了这样的功能，那么“生成lock.json”这个按钮就必需根据现在所显示的view来做了，不然的话，你现在显示的未被选中的圣遗物，然后想要下载加锁的lock.json，这部分逻辑会让人很困惑。
而显示未被选中的圣遗物的toggle可以保证被选中的圣遗物永远会显示，这样在“生成lock.json”按钮的下拉菜单里，加锁、加解锁就有了UI上的context（当然仅解锁就没有这层context了，但这个功能的使用频率比其他两个少得多）

2023-03-15 02:01 UTC, wengh commented on src/features/artifacts/ArtifactsUpload.jsx
> +    { name: "isInverted", defaultValue: false, replace: false },
在微调参数时，处于阈值附近的圣遗物的选中状态会随着参数微调而改变，所以我认为UI需要做到能方便地查看阈值附近的圣遗物，方便微调。

> 这个功能并不必需“仅显示未被选中的圣遗物”

目前的UI能通过排序（从低到高）方便地查看阈值附近的，超过阈值的圣遗物，而我们希望添加一些选项，做到同样方便地查看阈值附近，但是低于阈值的圣遗物。但是如果把所有圣遗物放在一起显示的话，就没办法通过排序将阈值附近的圣遗物显示在顶部了。想要看到的话只能不断翻页，去手动查找。而如果能只显示不满足条件的圣遗物，就可以用同样的方法，从高到低排序来查看接近但是低于阈值的圣遗物

> 是因为如果一旦做了这样的功能，那么“生成lock.json”这个按钮就必需根据现在所显示的view来做了

可以问一下这样有什么缺点吗？我觉得生成lock.json时只包含显示的圣遗物，好像还挺直观的

2023-03-16 20:19 UTC, LeiShi1313 requested changes

2023-03-16 20:19 UTC, LeiShi1313 commented on src/features/artifacts/ArtifactsUpload.jsx
> +    { name: "isInverted", defaultValue: false, replace: false },
没什么缺点，但是这么做的话，生成lock.json的按钮就不要做成下拉的了，就需要跟当前的选择状态匹配了，比如全选那就加解锁，只选选中的那就加锁，只选未选中的那就解锁

2023-03-18 00:11 UTC, wengh commented on src/features/artifacts/ArtifactsUpload.jsx
> +    { name: "isInverted", defaultValue: false, replace: false },
那我试着实现以下这个思路

2023-11-12 23:45 UTC, wang-hui commented
请问这个PR有什么进展吗？真的很需要这个工具能够改变已经加锁的圣遗物

2023-11-13 10:25 UTC, LeiShi1313 commented
> 请问这个PR有什么进展吗？真的很需要这个工具能够改变已经加锁的圣遗物

原作者一直没出现，你具体的需求是什么呢？

2023-11-13 12:41 UTC, wang-hui commented
> > 请问这个PR有什么进展吗？真的很需要这个工具能够改变已经加锁的圣遗物
> 
> 原作者一直没出现，你具体的需求是什么呢？

感谢回复。请问筛选掉的狗粮可以在lock.json中解锁吗？
也就是“所见即所得”：贵工具显示的圣遗物全部加锁，未显示的全部解锁

2023-11-13 16:15 UTC, LeiShi1313 commented
> > > 请问这个PR有什么进展吗？真的很需要这个工具能够改变已经加锁的圣遗物
> > 
> > 
> > 原作者一直没出现，你具体的需求是什么呢？
> 
> 感谢回复。请问筛选掉的狗粮可以在lock.json中解锁吗？ 也就是“所见即所得”：贵工具显示的圣遗物全部加锁，未显示的全部解锁

理论上是可以的，用yas-lock的v2lock文件可以，但是yas-lock的作者现在放弃项目了，所以这边大概率也不好做。

2023-11-13 16:24 UTC, wang-hui commented
> > > > 请问这个PR有什么进展吗？真的很需要这个工具能够改变已经加锁的圣遗物
> > > 
> > > 
> > > 原作者一直没出现，你具体的需求是什么呢？
> > 
> > 
> > 感谢回复。请问筛选掉的狗粮可以在lock.json中解锁吗？ 也就是“所见即所得”：贵工具显示的圣遗物全部加锁，未显示的全部解锁
> 
> 理论上是可以的，用yas-lock的v2lock文件可以，但是yas-lock的作者现在放弃项目了，所以这边大概率也不好做。

请问可以参考一下这个工具吗？https://ideless.github.io/artifact/
它是所见即所得，并且可以导出v2lock

2023-11-14 10:33 UTC, LeiShi1313 commented
> https://ideless.github.io/artifact/

对，这也是yas-lock作者的项目，估计以后也不维护了

2023-11-14 14:06 UTC, wang-hui commented
> > https://ideless.github.io/artifact/
> 
> 对，这也是yas-lock作者的项目，估计以后也不维护了

嗯嗯，好多人在那个工具不更新了之后转到了你这边。
我觉得(sorry for being naive)解锁已加锁的圣遗物这一功能并不需要持续维护？

2023-11-14 14:13 UTC, LeiShi1313 commented
> > > https://ideless.github.io/artifact/
> > 
> > 
> > 对，这也是yas-lock作者的项目，估计以后也不维护了
> 
> 嗯嗯，好多人在那个工具不更新了之后转到了你这边。 我觉得(sorry for being naive)解锁已加锁的圣遗物这一功能并不需要持续维护？

新圣遗物出来之后就需要的，其实主要问题是yas-lock离主线yas现在已经差距蛮大的了，不然我应该也可以维护yas-lock

2023-11-14 14:15 UTC, wang-hui commented
> > > > https://ideless.github.io/artifact/
> > > 
> > > 
> > > 对，这也是yas-lock作者的项目，估计以后也不维护了
> > 
> > 
> > 嗯嗯，好多人在那个工具不更新了之后转到了你这边。 我觉得(sorry for being naive)解锁已加锁的圣遗物这一功能并不需要持续维护？
> 
> 新圣遗物出来之后就需要的，其实主要问题是yas-lock离主线yas现在已经差距蛮大的了，不然我应该也可以维护yas-lock

哦哦，明白了。谢谢回复。

2023-11-14 14:18 UTC, LeiShi1313 commented
> > > > > https://ideless.github.io/artifact/
> > > > 
> > > > 
> > > > 对，这也是yas-lock作者的项目，估计以后也不维护了
> > > 
> > > 
> > > 嗯嗯，好多人在那个工具不更新了之后转到了你这边。 我觉得(sorry for being naive)解锁已加锁的圣遗物这一功能并不需要持续维护？
> > 
> > 
> > 新圣遗物出来之后就需要的，其实主要问题是yas-lock离主线yas现在已经差距蛮大的了，不然我应该也可以维护yas-lock
> 
> 哦哦，明白了。谢谢回复。

总之，这边我可以看下生成v2的lock文件看看，yas-lock的话等我学完rust看能不能fork过来继续更新吧

2023-11-19 21:44 UTC, LeiShi1313 commented
Fixed with [712636](https://github.com/LeiShi1313/genshin-aritifact-analyzer/commit/712636679176caf832e9bee625419acfb43eb831)

2023-11-19 21:44 UTC, closed without merging